<a href="https://colab.research.google.com/github/vedantiraut15/Artificial_Intelligence_Lab_SE-A-50/blob/master/Practical_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Calculate the determinant of 3x3 matrix

In [1]:
a = [
    [1, 2, 5],
    [2, 7, 3],
    [2, 4, 7]
]

det = (
    a[0][0] * (a[1][1]*a[2][2] - a[1][2]*a[2][1])
    - a[0][1] * (a[1][0]*a[2][2] - a[1][2]*a[2][0])
    + a[0][2] * (a[1][0]*a[2][1] - a[1][1]*a[2][0])
)

print("Determinant:", det)

Determinant: -9


Find the inverse of the matrix

In [3]:
import numpy as np

A = np.array([
    [1, 2, 5],
    [2, 7, 3],
    [2, 4, 7]
])

# Find inverse
A_inv = np.linalg.inv(A)

print("Matrix A:")
print(A)

print("\nInverse of A:")
print(A_inv)

Matrix A:
[[1 2 5]
 [2 7 3]
 [2 4 7]]

Inverse of A:
[[-4.11111111 -0.66666667  3.22222222]
 [ 0.88888889  0.33333333 -0.77777778]
 [ 0.66666667  0.         -0.33333333]]


 Solve the following system of linear equations using NumPy: 2x+3y=10, 4x+5y=20

In [4]:
import numpy as np

# Coefficient matrix
A = np.array([
    [2, 3],
    [4, 5]
])

# Constant matrix
B = np.array([10, 20])

# Solve the system
solution = np.linalg.solve(A, B)

print("Solution:")
print("x =", solution[0])
print("y =", solution[1])

Solution:
x = 5.0
y = 0.0
